[manifest]
version = "1.0.0"
dump_lua = true
priority = 2

# Round UI uses func
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R, config={align = "cm", maxw = 1.35}, nodes={
                  {n=G.UIT.T, config={text = localize('k_round'), minh = 0.33, scale = 0.85*scale, colour = G.C.UI.TEXT_LIGHT, shadow = true}},
                }},
                {n=G.UIT.R, config={align = "cm", r = 0.1, minw = 1.2, colour = temp_col2, id = 'row_round_text'}, nodes={
                  {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'round'}}, colours = {G.C.IMPORTANT},shadow = true, scale = 2*scale}),id = 'round_UI_count'}},
                }},'''
position = "at"
payload = '''roundUI(),'''
match_indent = true

# Remove UI effect
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local round_UI = G.hand_text_area.round
          mod = mod or 0'''
position = 'after'
payload = '''
if (not round_UI) or (G.GAME and G.GAME.SGTMD_timer) then
        G.GAME.round = G.GAME.round + mod
        check_and_set_high_score('furthest_round', G.GAME.round)
        check_and_set_high_score('furthest_ante', G.GAME.round_resets.ante)
        play_sound('timpani', 0.8)
        play_sound('generic1')
    return true
end
'''
match_indent = true